// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxokuotmxlosyaupbixa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94b2t1b3RteGxvc3lhdXBiaXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjI5MDAsImV4cCI6MjA2NTU5ODkwMH0.3R0s38vKgtP4BC64VaMaxgEP1OwsWcioFLfluIAm5BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);